feat: add `<PrismicLink>` component
prismicio/prismic-svelte pull request #4
Opened 2023-02-09 11:31 UTC by samlfair

## Types of changes

- [ ] Chore (a non-breaking change which is related to package maintenance)
- [ ] Bug fix (a non-breaking change which fixes an issue)
- [x] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Description

Add a `<PrismicLink>` component that can accept a Link field, Content Relationship field, or entire Document, and output an `<a>` element.

`<PrismicLink>` accepts all [SvelteKit link options](https://kit.svelte.dev/docs/link-options) and all [HTML link attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a) as props. It also accepts a Link Resolver.

## Checklist:

- [x] My change requires an update to the official documentation.
- [x] All [TSDoc](https://tsdoc.org) comments are up-to-date and new ones have been added where necessary.
- [x] All new and existing tests are passing.

![puppies](https://images.unsplash.com/photo-1611493568324-f556a0360e77?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1277&q=80)

2023-02-17 00:02 UTC, angeloashmore requested changes
Nice set of improvements to `<PrismicLink>`! 😃

We can make some optimization to the code to simplify its logic and readability. I left detailed comments on the code, but in summary:

- Use `$$Props` to extend Svelte's native anchor props.
- Compute `rel` and `target` using simpler logic.
- Look for ways to write less code with the same output, sometimes taking advantage of default behaviors.

Let me know if you have any questions or would like to work on a refactor together. 🙂

2023-02-23 16:07 UTC, samlfair commented on src/lib/components/PrismicLink.svelte
> +	// import { usePrismic } from "../usePrismic";
✅

2023-02-23 16:07 UTC, samlfair commented on src/lib/components/PrismicLink.svelte
> +	}
✅

2023-02-23 16:08 UTC, samlfair commented on src/lib/components/PrismicLink.svelte
>  	const href: string = link || "";
✅

2023-02-23 16:08 UTC, samlfair commented on src/lib/components/PrismicLink.svelte
> +	data-sveltekit-noscroll={sveltekitNoscroll || "off"}
Yep, this looks good to me.

2023-02-23 16:10 UTC, samlfair commented on src/lib/components/PrismicLink.svelte
>  	{...attrs}
Nope, I think you're right that `...$$restProps` handles this much more clenly.

2023-02-23 16:11 UTC, samlfair commented on src/lib/components/PrismicLink.svelte
> +	export let linkResolver: prismicH.LinkResolverFunction | null | undefined = null
Good to know! I learned the opposite in bootcamp, but I'm happy to follow this rule ✅

2023-02-23 16:12 UTC, samlfair commented on src/lib/components/PrismicLink.svelte
>  	{...attrs}
✅

2023-02-23 16:18 UTC, samlfair commented
@angeloashmore Thanks again for your feedback. I think I've addressed everything, and I responded to your question about `rel="external"`. Let me know what you think. When things are looking good, I can merge and publish this.

2023-02-23 21:11 UTC, angeloashmore commented on src/lib/components/PrismicLink.svelte
> +			}
👍 Sounds good to me. It was a question of, "Will SvelteKit work normally without `rel="external"`?"

With the updated code, developers can add `rel="external"` manually, so I think we have all of our bases covered.

2023-02-23 21:13 UTC, angeloashmore approved these changes

2023-02-23 21:13 UTC, angeloashmore commented
It looks great to me! Let's merge and publish. 🙂

2023-02-24 11:22 UTC, merged

2023-02-24 11:44 UTC, samlfair commented
Published 🚀